language:
- ruby
rvm:
- 2.5.0
cache:
- bundler
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
env:
  global:
    -CC_TEST_REPORTER_ID=766e664dae0f727b6f668b11deec5c2516ffe52f9479a1b9eefdd1edbcba1dfa
after_script:
  - bundle exec rake coveralls:push
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: "AJzsu99WFCnGcfdtuNE1Lg5Cz3oAjOWp9JEUPJ763cVTLI1KzdID5PCWVk44dySJsECG07OsWRzke8rkcvzxZUqIJq3fYqOch+LcgVxMsm4XWlwWZihmER2vcfcFpp1Z8QCXYAvjaYbQpn2qtGb9IIhRz9pLaQjFhi9mCorF64lIzFk16TanetCpnSHIVox0TGaVmSF1oGi9Jdp/p5XKTbvRC3i37QT+jWWaILe3OInSC4G5nx0spv4vg5gNjIH5ONFBFoXjd60i+z/fQhZ5wTxiRBcdSbyqg/6KGQLnJe0eoFfldSmpsmMZapfvU8Xv+H1OsJLBhkQS3gIWpaykoFBA7qy3tnSBNmz8O4L3YUl5W/jxTQJvSQTaj7oU4Lv2xopWuZLBTEG/re/ph+Y/iHODEoixmxv61N9GKhoadVe50CouiRuOAEOjw9Xe1Xn29l2puSPcbVtfX2IueB1BGHojVZEWQZA9H2q66i8pW+YRlYWK341NMkrB5gGvjKP2qat0skSljBkk5teVkuZ8Pgvek8U0UinlVzxynQmT4QpDl7BRG9cZEaXqP2wyxD1ggUJJdibGS6+i2CYIuzITPjq0JaydvXWZBggVghn9+GGSoQxnRFRW0V6pJelex4llmuXSgjlS6hKqIKPJi8nBbKfxZQEsXn+bOx0csrVwyzY="
  app: acebook-cats
  on:
    repo: learningtocode101/acebook-team-cats
